{% set name = "aws-c-sdkutils" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 17bdec593f3ae8a837622ef81055db81cc2dd14b86d33b21df878a7ab918d0e4

build:
  number: 3
  run_exports:
    - {{ pin_subpackage("aws-c-sdkutils", max_pin="x.x.x") }}

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-sdkutils${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/sdkutils/sdkutils.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\sdkutils\\sdkutils.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-sdkutils.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-sdkutils
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C.

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
