{% set name = "aws-c-sdkutils" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4a818563d7c6636b5b245f5d22d4d7c804fa33fc4ea6976e9c296d272f4966d3

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-sdkutils", max_pin="x.x.x") }}

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-sdkutils${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/sdkutils/sdkutils.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\sdkutils\\sdkutils.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-sdkutils.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-sdkutils
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C.

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
